/* Geolite - traducciones (v0.9): textos nuevos de la Aventura por temas, tienda y menu. Se suman a A.TR (js/i18n2.js). [fr, pt, de, it, es-419, zh, ko, ja, ru, pl] */
window.AIQ = window.AIQ || {};
(function (A) {
  Object.assign(A.TR = A.TR || {}, {
    "Doubloons ×2": ["Doublons ×2", "Dobrões ×2", "Dublonen ×2", "Dobloni ×2", "Doblones ×2", "金币 ×2", "도블론 ×2", "ダブロン×2", "Дублоны ×2", "Dublony ×2"],
    "No cards left: move on!": ["Plus de cartes : en avant !", "Não restam cartas: siga em frente!", "Keine Karten mehr: weiter geht's!", "Niente più carte: avanti!", "No quedan cartas: ¡a seguir!", "没有更多卡牌了：继续前进吧！", "남은 카드가 없습니다: 계속 진행하세요!", "カードがもうない：先へ進もう！", "Карт больше нет: продолжаем!", "Koniec kart: ruszaj dalej!"],
    "Pick ONE relic for free. Legendaries can show up here.": ["Choisis UNE relique gratuite. Des légendaires peuvent apparaître ici.", "Escolha UMA relíquia de graça. Aqui podem aparecer lendárias.", "Wähle EIN Relikt kostenlos. Hier können Legendäre auftauchen.", "Scegli UNA reliquia gratis. Qui possono uscire le leggendarie.", "Elige UNA reliquia gratis. Aquí pueden aparecer legendarias.", "免费选择一件遗物。这里可能出现传说级遗物。", "유물 하나를 무료로 선택하세요. 여기서는 전설 유물도 나올 수 있습니다.", "レリックを1つ無料で選ぼう。ここではレジェンダリーも出現する。", "Выбери ОДНУ реликвию бесплатно. Здесь могут появиться легендарные.", "Wybierz JEDEN relikt za darmo. Mogą się tu trafić legendarne."],
    "free": ["gratuit", "grátis", "gratis", "gratis", "gratis", "免费", "무료", "無料", "бесплатно", "za darmo"],
    "You scored {s} of {a}. You have {n} provisions left.": ["Tu as fait {s} sur {a}. Il te reste {n} provisions.", "Você fez {s} de {a}. Restam {n} provisões.", "Du hast {s} von {a} erreicht. Dir bleiben {n} Proviant.", "Hai fatto {s} su {a}. Ti restano {n} provviste.", "Conseguiste {s} de {a}. Te quedan {n} provisiones.", "你得了 {s} / {a} 分。还剩 {n} 份补给。", "{a}점 중 {s}점을 얻었습니다. 식량이 {n}개 남았습니다.", "{a}のうち{s}を獲得。食料は残り{n}。", "Набрано {s} из {a}. Осталось запасов: {n}.", "Wynik: {s} z {a}. Zostało ci zapasów: {n}."],
    "Reset Encyclopedia": ["Réinitialiser l'Encyclopédie", "Redefinir a Enciclopédia", "Enzyklopädie zurücksetzen", "Ripristina l'Enciclopedia", "Restablecer la Enciclopedia", "重置百科全书", "도감 초기화", "図鑑をリセット", "Сбросить энциклопедию", "Wyczyść Encyklopedię"],
    "Deletes every unlocked card. Your profile, achievements and records stay.": ["Supprime toutes les cartes débloquées. Ton profil, tes succès et tes records restent.", "Apaga todas as cartas desbloqueadas. Seu perfil, conquistas e recordes continuam.", "Löscht alle freigeschalteten Karten. Profil, Erfolge und Rekorde bleiben.", "Elimina tutte le carte sbloccate. Profilo, obiettivi e record restano.", "Borra todas las tarjetas desbloqueadas. Tu perfil, logros y récords se mantienen.", "删除所有已解锁的卡片。你的个人资料、成就与记录会保留。", "잠금 해제된 모든 카드를 삭제합니다. 프로필, 업적, 기록은 유지됩니다.", "アンロック済みのカードをすべて削除します。プロフィール、実績、記録は残ります。", "Удаляет все разблокированные карточки. Профиль, достижения и рекорды сохранятся.", "Usuwa wszystkie odblokowane karty. Profil, osiągnięcia i rekordy zostają."],
    "Sure? Press again to delete": ["Sûr ? Appuie encore pour supprimer", "Tem certeza? Pressione de novo para apagar", "Sicher? Nochmal drücken zum Löschen", "Sicuro? Premi ancora per eliminare", "¿Seguro? Presiona otra vez para borrar", "确定吗？再点一次以删除", "정말요? 삭제하려면 한 번 더 누르세요", "本当に？削除するにはもう一度押してください", "Точно? Нажми ещё раз, чтобы удалить", "Na pewno? Naciśnij ponownie, by usunąć"],
    "Encyclopedia reset": ["Encyclopédie réinitialisée", "Enciclopédia redefinida", "Enzyklopädie zurückgesetzt", "Enciclopedia ripristinata", "Enciclopedia restablecida", "百科全书已重置", "도감이 초기화되었습니다", "図鑑をリセットしました", "Энциклопедия сброшена", "Encyklopedia wyczyszczona"],
  });
})(window.AIQ);
