/*
 * Geolite - TEXTOS CON MANDO (v0.2.30). Las instrucciones que hablan de raton, clic o rueda tienen aqui su version para mando:
 * A.PADV["texto en espanol"] = "es|en|fr|pt|de|it|es-419|zh|ko|ja|ru|pl". A.pick6 y A.tx (js/support.js) la eligen solas cuando
 * html[data-glyph] no es "kb" (js/mando.js); {A} es el boton de confirmar de ese mando (A, o la cruz en PlayStation).
 * Las frases del crupier que hablan del raton o del clic, sin version aqui, simplemente no se dicen con mando (js/dealer.js).
 */
window.AIQ = window.AIQ || {};
window.AIQ.PADV = {
  "Haz clic en el mapa donde crees que está. Con la rueda o los botones + y − haces zoom. Cuanto más cerca, más puntos.":
    "Mueve la mira con el stick izquierdo y pulsa {A} donde crees que está. Con los gatillos haces zoom y con el stick derecho mueves el mapa. Cuanto más cerca, más puntos.|Move the crosshair with the left stick and press {A} where you think it is. Zoom with the triggers and move the map with the right stick. The closer you are, the more points.|Déplace le viseur avec le stick gauche et appuie sur {A} là où tu penses qu'il se trouve. Les gâchettes zooment et le stick droit déplace la carte. Plus tu es proche, plus tu gagnes de points.|Mova a mira com o analógico esquerdo e aperte {A} onde você acha que ele está. Os gatilhos dão zoom e o analógico direito move o mapa. Quanto mais perto, mais pontos.|Bewege das Fadenkreuz mit dem linken Stick und drücke {A}, wo du ihn vermutest. Mit den Triggern zoomst du, mit dem rechten Stick verschiebst du die Karte. Je näher, desto mehr Punkte.|Muovi il mirino con la levetta sinistra e premi {A} dove pensi che sia. Con i grilletti fai zoom e con la levetta destra sposti la mappa. Più sei vicino, più punti ottieni.|Mueve la mira con el stick izquierdo y presiona {A} donde crees que está. Con los gatillos haces zoom y con el stick derecho mueves el mapa. Cuanto más cerca, más puntos.|用左摇杆移动准星，在你认为它所在的位置按 {A}。用扳机键缩放，用右摇杆移动地图。越接近，得分越高。|왼쪽 스틱으로 조준점을 움직이고 있다고 생각하는 곳에서 {A}를 누르세요. 트리거로 확대/축소하고 오른쪽 스틱으로 지도를 움직여요. 가까울수록 점수가 높아요.|左スティックで照準を動かし、あると思う場所で{A}を押そう。トリガーでズーム、右スティックで地図を動かせる。近いほど高得点。|Двигай прицел левым стиком и нажми {A} там, где, по-твоему, это место. Триггеры меняют масштаб, правый стик двигает карту. Чем ближе, тем больше очков.|Przesuwaj celownik lewą gałką i naciśnij {A} tam, gdzie twoim zdaniem leży. Spustami przybliżasz, prawą gałką przesuwasz mapę. Im bliżej, tym więcej punktów.",
  "Tus herramientas: púlsalas (o su número) para usarlas. Dan pistas, como a cuántos km o hacia dónde está el lugar, y se recargan cada ronda.":
    "Tus herramientas: llega a ellas con la cruceta y pulsa {A} para usarlas. Dan pistas, como a cuántos km o hacia dónde está el lugar, y se recargan cada ronda.|Your tools: reach them with the D-pad and press {A} to use them. They give clues, like how many km away or which way the place is, and refill every round.|Tes outils : atteins-les avec la croix directionnelle et appuie sur {A}. Ils donnent des indices, comme la distance en km ou la direction du lieu, et se rechargent à chaque manche.|Suas ferramentas: chegue nelas com o direcional e aperte {A} para usá-las. Dão pistas, como a quantos km ou em que direção fica o lugar, e recarregam a cada rodada.|Deine Werkzeuge: Steuere sie mit dem Steuerkreuz an und drücke {A}. Sie geben Hinweise, etwa Entfernung in km oder Richtung des Ortes, und laden sich jede Runde auf.|I tuoi strumenti: raggiungili con la croce direzionale e premi {A} per usarli. Danno indizi, come la distanza in km o la direzione del luogo, e si ricaricano a ogni round.|Tus herramientas: llega a ellas con la cruceta y presiona {A} para usarlas. Dan pistas, como a cuántos km o hacia dónde está el lugar, y se recargan cada ronda.|你的工具：用十字键选中，按 {A} 使用。它们会提供线索，比如距离多少公里或地点在哪个方向，每回合都会补满。|도구: 방향 패드로 고른 뒤 {A}를 눌러 사용하세요. 몇 km 떨어졌는지, 어느 방향인지 같은 단서를 주고, 매 라운드 다시 채워져요.|道具：十字キーで選んで{A}で使う。何km離れているか、どの方向かなどのヒントをくれて、毎ラウンド補充される。|Твои инструменты: выбери их крестовиной и нажми {A}. Они дают подсказки — сколько км до места или в какой оно стороне — и пополняются каждый раунд.|Twoje narzędzia: wybierz je krzyżakiem i naciśnij {A}. Podpowiadają np. ile km dzieli cię od miejsca albo w którą stronę leży, i odnawiają się co rundę.",
  "Mueve el ratón para despertar la pantalla":
    "Mueve el stick para despertar la pantalla|Move the stick to wake the screen|Bouge le stick pour réveiller l'écran|Mova o analógico para acordar a tela|Bewege den Stick, um den Bildschirm zu wecken|Muovi la levetta per riattivare lo schermo|Mueve el stick para despertar la pantalla|移动摇杆唤醒屏幕|스틱을 움직여 화면을 깨우세요|スティックを動かして画面を起こす|Подвигай стиком, чтобы разбудить экран|Porusz gałką, by obudzić ekran",
  "La pantalla entra en reposo cuando menos lo esperas: tu primer clic solo la despierta.":
    "La pantalla entra en reposo cuando menos lo esperas: tu primera pulsación solo la despierta.|The screen goes to sleep when you least expect it: your first press only wakes it up.|L'écran se met en veille quand tu t'y attends le moins : ta première pression ne fait que le réveiller.|A tela entra em repouso quando você menos espera: o primeiro botão que você aperta só serve para acordá-la.|Der Bildschirm geht in den Ruhemodus, wenn du es am wenigsten erwartest: Dein erster Tastendruck weckt ihn nur auf.|Lo schermo va in standby quando meno te lo aspetti: la tua prima pressione serve solo a svegliarlo.||屏幕会在你最意想不到的时候进入休眠：你的第一次按键只会把它唤醒。|화면이 가장 예상치 못한 순간에 절전 모드로 들어갑니다. 첫 버튼 입력은 화면을 깨우기만 합니다.|画面は思いもよらないタイミングでスリープに入る。最初のボタンは画面を起こすだけ。|Экран засыпает, когда ты меньше всего ждёшь: первое нажатие его только разбудит.|Ekran zasypia, gdy najmniej się tego spodziewasz: pierwsze naciśnięcie tylko go obudzi.",
  "A veces la pantalla se me queda en reposo. Tu primer clic solo la despierta.":
    "A veces la pantalla se me queda en reposo. Tu primera pulsación solo la despierta.|Sometimes my screen drifts into standby. Your first press only wakes it.|Parfois mon écran se met en veille. Ta première pression ne fait que le réveiller.|Às vezes minha tela entra em repouso. O primeiro botão que você aperta só serve para acordá-la.|Manchmal fällt mein Bildschirm in den Standby. Dein erster Tastendruck weckt ihn nur auf.|A volte il mio schermo va in standby. La tua prima pressione serve solo a svegliarlo.||有时候我的屏幕会进入待机。你的第一次按键只会把它唤醒。|가끔 제 화면이 대기 모드로 들어가요. 첫 버튼 입력은 화면을 깨우기만 해요.|たまに私の画面はスタンバイになるんだ。最初のボタンは起こすだけだよ。|Иногда мой экран уходит в спящий режим. Первое нажатие его только разбудит.|Czasem mój ekran przechodzi w tryb czuwania. Pierwsze naciśnięcie tylko go obudzi.",
  "El humo tapa el mapa: apártalo con el ratón.":
    "El humo tapa el mapa: apártalo moviendo la mira.|Smoke covers the map: sweep it away by moving the crosshair.|La fumée cache la carte : chasse-la en bougeant le viseur.|A fumaça cobre o mapa: afaste-a movendo a mira.|Rauch verdeckt die Karte: Wisch ihn mit dem Fadenkreuz weg.|Il fumo copre la mappa: scaccialo muovendo il mirino.||烟雾遮住了地图：移动准星把它拨开。|연기가 지도를 가립니다: 조준점을 움직여 걷어내세요.|煙が地図を覆う。照準を動かして払いのけよう。|Дым закрывает карту: разгони его, двигая прицел.|Dym zasłania mapę: rozgoń go, ruszając celownikiem.",
  "La lluvia empaña el mapa: agita el ratón para limpiarla.":
    "La lluvia empaña el mapa: agita el stick izquierdo para limpiarla.|Rain fogs up the map: wiggle the left stick to wipe it.|La pluie embue la carte : secoue le stick gauche pour l'essuyer.|A chuva embaça o mapa: sacuda o analógico esquerdo para limpar.|Regen beschlägt die Karte: Wackle mit dem linken Stick, um sie abzuwischen.|La pioggia appanna la mappa: scuoti la levetta sinistra per pulirla.||雨水让地图变得模糊：晃动左摇杆把它擦干净。|비가 지도를 흐리게 합니다: 왼쪽 스틱을 흔들어 닦아내세요.|雨で地図が曇る。左スティックを振って拭き取ろう。|Дождь заливает карту: покачай левым стиком, чтобы протереть её.|Deszcz zamazuje mapę: porusz lewą gałką, by ją przetrzeć.",
  "Países (haz clic dentro)":
    "Países (apunta dentro)|Countries (aim inside)|Pays (vise dedans)|Países (mire dentro)|Länder (ziele hinein)|Paesi (mira dentro)||国家（瞄准国境内）|국가 (안쪽을 조준)|国（国内を狙う）|Страны (целься внутрь)|Kraje (celuj w środek)",
  "{s} s sin tocar el ratón":
    "{s} s sin tocar el mando|{s} s without touching the controller|{s} s sans toucher la manette|{s} s sem tocar no controle|{s} s ohne den Controller zu berühren|{s} s senza toccare il controller|{s} s sin tocar el control|{s} 秒没碰手柄|{s}초 동안 패드 안 만지기|{s}秒コントローラーに触れず|{s} с без геймпада|{s} s bez dotykania pada",
};
/* el boton de confirmar escrito: A en Xbox y Steam Deck; la cruz en PlayStation, con su nombre en cada idioma */
window.AIQ.PADCONF = { ps: "Cruz|Cross|Croix|X|Kreuz|Croce|X|×|X|×|Крест|Krzyżyk" };
