/*
 * Geolite - catalogo de PERKS de la Aventura (v0.10). Ninguno multiplica ni suma puntos: la puntuacion es solo tu precision.
 * Los perks ayudan a resolver los RETOS del crupier (letras temblorosas, mapa borroso, apagon, fronteras falsas, continentes movidos...),
 * mejoran tu puntero, dan pistas, tiempo, supervivencia o doblones. Cada perk es una carta de poker con palo geografico.
 *
 *   fx {..}         mitigaciones de retos y mejoras del puntero (ver A.chal.fx en js/challenges.js)
 *   round(x,run)    al empezar la ronda (x.seconds)                open(api,o,run)  pistas gratis al empezar cada pregunta (api.laterHalf: a mitad de tiempo)
 *   clear(x,run)    al superar una ronda (x.coins)                 shop(x,run)      tienda (x.price -, x.freeReroll)   buy(run) / sell(run)  al comprarla / venderla
 *   post(c,run)     tras puntuar: SOLO doblones (c.coins)          flags: immune[], softenBoss, skipHardest, guard, marginHalf, ventaja, amulet, coinX, toolBonus, interest, shieldAct, sonarErr, compass16, spy, skipFirst
 *   hint            pista gratis: "continent", "country" (ilumina el pais) o "note" (nota de campo). La tienda solo la ofrece si aporta en lo que queda (useful)
 * Texto: n = nombre y d = descripcion en es|en|fr|pt|de|it|es-419|zh|ko|ja|ru|pl (es-419 vacio = espanol).
 */
window.AIQ = window.AIQ || {};
(function (A) {
  const L6 = A.L6;
  const P = {};
  const def = (id, suit, cost, r, n, d, hooks = {}) => { P[id] = { id, ico: id, suit, cost, r, n: L6(n), d: L6(d), ...hooks }; };
  const seeded = (run, tag) => A.rng(`${run.seed}:${tag}:${run.act}:${run.round}:${run.qi}:${run.qTotal || 0}`)();

  /* tanda 3: las contras son AMULETOS (amulet = su familia de retos, js/challenges.js FAMC): ocupan un hueco y actuan siempre que sale su familia.
     0.2.5: sin cargas (ya no se gastan ni se parten); contra un reto a nivel 3 solo lo suavizan: sus efectos a medias (amuSoft en js/adventure.js) */
  /* ---------------------------------------------------------------- contra retos de TEXTO */
  def("steadyhand", "s_compass", 4, 0, "Mano firme|Steady hand|Main ferme|Mão firme|Ruhige Hand|Mano ferma||稳手|흔들림 없는 손|揺るがぬ手|Твёрдая рука|Pewna ręka", "Tu puntero no tiembla, no se esconde, no se retrasa ni se invierte.|Your pointer won't shake, hide, lag or flip.|Ton pointeur ne tremble, ne se cache, ne traîne ni ne s'inverse.|Seu ponteiro não treme, não some, não atrasa nem inverte.|Kein Zittern, Verschwinden, Nachhängen oder Umkehren mehr für deinen Zeiger.|Il puntatore non trema, non sparisce, non ritarda e non si inverte.||指针不再抖动、消失、延迟或反向。|포인터가 떨리거나 사라지거나 늦거나 뒤집히지 않아요.|ポインターが震えず、消えず、遅れず、逆にもならない。|Курсор не дрожит, не исчезает, не отстаёт и не переворачивается.|Kursor nie drży, nie znika, nie spóźnia się i nie odwraca.", { amulet: "puntero", fx: { ptrShakeMul: 0.25, ptrBlurMul: 0.2, lagMul: 0.001, noBlink: true, ghostMul: 0.4, beacon: true, unmirrorPtr: true } });
  def("dictionary", "s_peak", 4, 0, "Chuleta|Cheat sheet|Antisèche|Cola|Spickzettel|Bigliettino|Acordeón|小抄|커닝 페이퍼|カンペ|Шпаргалка|Ściąga", "Las letras trucadas, giradas o borradas del nombre se arreglan.|Tricked, flipped or faded letters in the name get fixed.|Les lettres truquées, retournées ou effacées du nom se réparent.|Letras trocadas, viradas ou apagadas do nome se consertam.|Getrickste, gedrehte oder verblasste Buchstaben im Namen werden repariert.|Le lettere truccate, capovolte o sbiadite del nome si aggiustano.||名字里被做手脚、翻转或抹掉的字母会恢复。|이름의 조작되거나 뒤집히거나 지워진 글자가 고쳐져요.|名前の細工・反転・消えた文字が元に戻る。|Подменённые, перевёрнутые и стёртые буквы названия исправляются.|Podmienione, odwrócone i wymazane litery nazwy wracają na miejsce.", { amulet: "letras", fx: { textShakeMul: 0.25, textMul: 0.5, noMarquee: true, missingRate: 0.9, unswapMs: 2000, decodeMs: 2000, keepName: true, unmirrorText: true } });

  /* ---------------------------------------------------------------- contra retos del MAPA */
  def("miner", "s_peak", 4, 0, "Foco|Spotlight|Projecteur|Holofote|Scheinwerfer|Riflettore||聚光灯|스포트라이트|スポットライト|Прожектор|Reflektor", "El Apagón, la Batería baja y la bandera a oscuras casi no tapan.|Blackout, Low battery and Flag in the dark barely hide anything.|La Panne de courant, la Batterie faible et le drapeau dans le noir ne cachent presque plus rien.|Apagão, Bateria fraca e bandeira no escuro quase não escondem nada.|Stromausfall, Akku schwach und die Flagge im Dunkeln verdecken kaum noch etwas.|Blackout, Batteria scarica e bandiera al buio non nascondono quasi nulla.||停电、电量不足和黑暗中的国旗几乎挡不住视线。|정전, 배터리 부족, 어둠 속의 국기가 거의 가리지 못해요.|停電、バッテリー残量低下、暗闇の国旗がほとんど邪魔にならない。|«Отключение света», «Низкий заряд» и флаг в темноте почти не мешают.|Awaria prądu, Słaba bateria i flaga w ciemności prawie nic nie zasłaniają.", { amulet: "luz", fx: { darkR: 1.9, halo: true, batteryMul: 0.3 } });
  def("divingmask", "s_palm", 4, 0, "Gafas de sol|Sunglasses|Lunettes de soleil|Óculos escuros|Sonnenbrille|Occhiali da sole|Lentes de sol|墨镜|선글라스|サングラス|Тёмные очки|Okulary przeciwsłoneczne", "Lo borroso, lo pixelado, el humo y la lluvia casi no tapan el mapa.|Blur, chunky pixels, smoke and rain barely hide the map.|Le flou, les gros pixels, la fumée et la pluie ne cachent presque plus la carte.|Borrão, pixels gordos, fumaça e chuva quase não escondem o mapa.|Unschärfe, grobe Pixel, Rauch und Regen verdecken die Karte kaum noch.|Sfocatura, pixel giganti, fumo e pioggia non coprono quasi più la mappa.||模糊、粗大像素、烟雾和雨几乎挡不住地图。|흐림, 큼직한 픽셀, 연기와 비가 지도를 거의 가리지 못해요.|ぼやけ、粗いピクセル、煙と雨が地図をほとんど隠さない。|Размытие, крупные пиксели, дым и дождь почти не закрывают карту.|Rozmycie, grube piksele, dym i deszcz prawie nie zasłaniają mapy.", { amulet: "vista", fx: { blurMul: 0.2, focusMul: 0.5, mosaicMul: 0.4, cloudMul: 0.5, rainMul: 0.35 } });
  def("plates", "s_palm", 4, 0, "Ancla|Anchor|Ancre|Âncora|Anker|Ancora||船锚|닻|錨|Якорь|Kotwica", "El mapa vuelve casi a su sitio, sin temblar, girar ni darse la vuelta.|The map snaps almost back into place: no shaking, spinning or flipping.|La carte revient presque à sa place, sans trembler, tourner ni se retourner.|O mapa volta quase ao lugar, sem tremer, girar nem virar.|Die Karte kehrt fast an ihren Platz zurück, ohne Beben, Drehen oder Kippen.|La mappa torna quasi al suo posto, senza tremare, ruotare né capovolgersi.|El mapa vuelve casi a su lugar, sin temblar, girar ni darse la vuelta.|地图几乎回到原位，不再晃动、旋转或翻转。|지도가 거의 제자리로 돌아오고 흔들리거나 돌거나 뒤집히지 않아요.|地図がほぼ元の位置に戻り、揺れも回転も反転もしない。|Карта почти возвращается на место — без тряски, вращения и переворотов.|Mapa wraca prawie na swoje miejsce, bez drżenia, obracania i odwracania.", { amulet: "sitio", fx: { plateMul: 0.4, quakeMul: 0.3, unmirrorMap: true } });

  /* ---------------------------------------------------------------- puntero */

  /* ---------------------------------------------------------------- pistas gratis y herramientas */
  def("sextant", "s_palm", 4, 0, "Soplo del crupier|Dealer's tip-off|Tuyau du croupier|Dica do crupiê|Tipp vom Croupier|Soffiata del croupier||荷官的暗示|딜러의 귀띔|ディーラーの耳打ち|Наводка крупье|Cynk od krupiera", "Te sopla en qué mitad del país está el lugar; en las pistas, la región.|Whispers which half of the country the place is in; in clues, the region.|Te souffle dans quelle moitié du pays se trouve le lieu ; dans les indices, la région.|Sopra em que metade do país fica o lugar; nas pistas, a região.|Flüstert dir, in welcher Hälfte des Landes der Ort liegt; bei Hinweisen die Region.|Ti suggerisce in quale metà del paese si trova il luogo; negli indizi, la regione.||悄悄告诉你地点在该国的哪一半；线索题则告诉你地区。|장소가 나라의 어느 쪽 절반에 있는지 귀띔합니다. 단서 문제에서는 지역을 알려줍니다.|場所が国のどちら半分にあるかを耳打ちする。ヒント問題では地域。|Шепнёт, в какой половине страны место; в подсказках — регион.|Podpowie, w której połowie kraju jest miejsce; przy wskazówkach — region.", { open: (api, o) => api.half(o), hint: "half" });   // tanda 10: la mitad del pais (antes, el continente: repetia lo que ya estaba escrito)
  def("almanac", "s_peak", 5, 1, "Libro de la casa|House ledger|Registre de la maison|Livro da casa|Hausregister|Registro della casa||赌场账簿|하우스 장부|ハウスの帳簿|Книга заведения|Księga kasyna", "En banderas y pistas te dice la región; en lo demás, una nota de campo.|In flags and clues it tells you the region; elsewhere, a field note.|Pour les drapeaux et les indices, il te donne la région ; ailleurs, une note de terrain.|Em bandeiras e pistas te diz a região; no resto, uma nota de campo.|Bei Flaggen und Hinweisen nennt es dir die Region, sonst eine Feldnotiz.|In bandiere e indizi ti dice la regione; altrove, una nota di campo.||国旗和线索题告诉你地区；其他题目给一条实地笔记。|국기와 단서 문제에서는 지역을, 나머지에서는 현장 메모를 알려줍니다.|国旗とヒント問題では地域を、それ以外ではフィールドノートを教える。|Во флагах и подсказках называет регион, в остальном — полевая заметка.|Przy flagach i wskazówkach podaje region, poza tym — notatkę terenową.", { open: (api, o) => api.fact(o), hint: "note" });   // tanda 10: sin la contra de la Adivinanza (pasa a SABER, sin contra)
  def("glass", "s_palm", 8, 2, "Catalejo|Spyglass|Longue-vue|Luneta|Fernrohr|Cannocchiale||望远镜|망원경|望遠鏡|Подзорная труба|Luneta", "+1 carga en tus herramientas; el Sonar y la Brújula, más precisos.|+1 charge on your tools; the Sonar and the Compass get more precise.|+1 charge pour tes outils ; le Sonar et la Boussole, plus précis.|+1 carga nas suas ferramentas; o Sonar e a Bússola, mais precisos.|+1 Ladung für deine Werkzeuge; Sonar und Kompass werden genauer.|+1 carica ai tuoi strumenti; Sonar e Bussola più precisi.||你的工具使用次数 +1；声呐和指南针更精准。|도구 충전 +1회; 소나와 나침반이 더 정확해집니다.|道具のチャージ+1。ソナーとコンパスがより正確に。|+1 заряд твоим инструментам; сонар и компас точнее.|+1 ładunek dla twoich narzędzi; Sonar i Kompas są dokładniejsze.", { toolBonus: 1, sonarErr: 0.02, compass16: true });   // tanda 9: junta el Sonar trucado y la Ruleta de 16 rumbos
  def("spyhole", "s_pin", 5, 1, "Ojo en el cielo|Eye in the sky|Œil dans le ciel|Olho no céu|Auge am Himmel|Occhio nel cielo||天眼|하늘의 눈|空の目|Око в небе|Oko na niebie", "Ves los retos de 2 rondas más y Barajas gratis una vez por visita, salvo jefes.|See challenges 2 rounds further ahead, and Reshuffle for free once per visit (not on bosses).|Tu vois les défis de 2 manches de plus et tu rebats gratis une fois par visite, sauf les boss.|Você vê os desafios de mais 2 rodadas e Embaralha grátis uma vez por visita, exceto chefes.|Du siehst die Herausforderungen von 2 weiteren Runden und mischst einmal pro Besuch gratis neu, außer bei Bossen.|Vedi le sfide di altri 2 round e rimescoli gratis una volta per visita, tranne i boss.||能看到之后 2 回合的挑战，每次到访可免费重新洗牌一次（首领除外）。|2라운드 뒤의 도전까지 보이고, 방문마다 한 번 무료로 다시 섞습니다 (보스 제외).|さらに2ラウンド先のチャレンジが見え、キャンプごとに1回無料でシャッフルできる（ボスを除く）。|Видишь испытания ещё на 2 раунда вперёд и раз за визит бесплатно перетасовываешь (кроме боссов).|Widzisz wyzwania 2 kolejnych rund i raz na wizytę tasujesz za darmo (poza bossami).", { spy: 2, freeShuffle: true });   // tanda 9: junta el Vale de la casa
  def("coolhead", "s_peak", 6, 1, "Sangre fría|Cool head|Sang-froid|Sangue-frio|Kaltblütig|Sangue freddo||冷静|침착함|冷静沈着|Хладнокровие|Zimna krew", "Con racha de 2 o más, se apagan los retos de tu puntero y de tu pantalla.|With a streak of 2 or more, challenges on your pointer and screen switch off.|Avec une série de 2 ou plus, les défis de ton pointeur et de ton écran s'éteignent.|Com sequência de 2 ou mais, os desafios do seu ponteiro e da sua tela se desligam.|Ab einer Serie von 2 schalten sich die Herausforderungen an Zeiger und Bildschirm ab.|Con una serie di 2 o più, le sfide su puntatore e schermo si spengono.||连击达到 2 或以上时，指针和屏幕上的挑战会关闭。|연속 기록이 2 이상이면 포인터와 화면의 도전이 꺼집니다.|連続正解が2以上になると、ポインターと画面のチャレンジが止まる。|При серии от 2 испытания курсора и экрана отключаются.|Przy serii 2 lub więcej wyzwania kursora i ekranu się wyłączają.", { calm: ["puntero", "pantalla"] });   // tanda 9: si sabes, el crupier deja de molestarte
  def("pact", "s_peak", 5, 1, "Pacto con la casa|Pact with the house|Pacte avec la maison|Pacto com a casa|Pakt mit dem Haus|Patto con la casa||与赌场的契约|하우스와의 계약|ハウスとの契約|Договор с заведением|Pakt z kasynem", "+1 hueco en la mochila. A cambio, cada ronda que no es jefe trae un reto más.|+1 backpack slot. In exchange, every non-boss round brings one more challenge.|+1 emplacement dans le sac. En échange, chaque manche hors boss apporte un défi de plus.|+1 espaço na mochila. Em troca, cada rodada que não é de chefe traz mais um desafio.|+1 Platz im Rucksack. Dafür bringt jede Runde ohne Boss eine Herausforderung mehr.|+1 posto nello zaino. In cambio, ogni round che non è un boss porta una sfida in più.||背包 +1 格。作为交换，每个非首领回合多一个挑战。|배낭 칸 +1. 대신 보스가 아닌 라운드마다 도전이 하나 더 나옵니다.|バッグの枠+1。代わりにボス以外のラウンドでチャレンジが1つ増える。|+1 ячейка в рюкзаке. Взамен каждый раунд без босса приносит ещё одно испытание.|+1 miejsce w plecaku. W zamian każda runda bez bossa przynosi jedno wyzwanie więcej.", { slot: 1, pact: true });   // tanda 13: un hueco mas en la mochila a cambio de un reto sellado en cada ronda que no es de jefe

  /* ---------------------------------------------------------------- tiempo */
  def("boots", "s_palm", 4, 0, "Cortesía de la casa|House comp|Cadeau de la maison|Cortesia da casa|Aufs Haus|Omaggio della casa||赌场赠品|하우스 서비스|ハウスのサービス|Подарок заведения|Prezent od kasyna", "+3 s por pregunta en las 12 rondas.|+3 s per question in all 12 rounds.|+3 s par question sur les 12 manches.|+3 s por pergunta nas 12 rodadas.|+3 s pro Frage in den 12 Runden.|+3 s per domanda nei 12 round.||12 个回合中每题 +3 秒。|12라운드 동안 문제당 +3초.|12ラウンドの間、1問につき+3秒。|+3 с на вопрос в 12 раундах.|+3 s na pytanie w 12 rundach.", { round: x => { x.seconds += 3; } });

  /* ---------------------------------------------------------------- economia (doblones y tienda) */
  def("purse", "s_pin", 4, 0, "Ficha de propina|Tip chip|Jeton de pourboire|Ficha de gorjeta|Trinkgeld-Chip|Fiche da mancia||小费筹码|팁 칩|ご祝儀チップ|Фишка на чай|Żeton napiwku", "+1 doblón por cada respuesta en racha (2.ª seguida o más).|+1 doubloon for each answer on a streak (2nd in a row or more).|+1 doublon par réponse en série (2e d'affilée ou plus).|+1 dobrão por resposta em sequência (2.ª seguida ou mais).|+1 Dublone für jede Antwort in Serie (ab der 2. in Folge).|+1 doblone per ogni risposta in serie (2ª di fila o più).||连击中的每个回答 +1 金币（连续第 2 个起）。|연속 기록 중인 답마다 도블론 +1 (2연속부터).|連続正解中の回答ごとに+1ダブロン（2連続目から）。|+1 дублон за каждый ответ в серии (со 2-го подряд).|+1 dublon za każdą odpowiedź w serii (od 2. z rzędu).", { post: c => (c.hit && c.streak >= 2 ? (c.coins += 1, "+1") : null) });   // tanda 9: atada a la racha (antes, a la precision)
  def("hoard", "s_pin", 5, 0, "Hucha|Piggy bank|Tirelire|Cofrinho|Sparschwein|Salvadanaio|Alcancía|存钱罐|돼지 저금통|貯金箱|Копилка|Skarbonka", "Cada ronda superada mete 3 doblones dentro. Al venderla, te los llevas.|Each round you clear puts 3 doubloons inside. Sell it to take them.|Chaque manche réussie y met 3 doublons. Vends-la pour les récupérer.|Cada rodada vencida põe 3 dobrões dentro. Ao vendê-lo, você leva tudo.|Jede geschaffte Runde wirft 3 Dublonen hinein. Verkauf es, um sie zu bekommen.|Ogni round superato ci mette dentro 3 dobloni. Vendilo per prenderli.||每通过一个回合就往里存 3 枚金币。卖掉它就能拿走。|라운드를 통과할 때마다 3도블론이 쌓입니다. 팔면 가져갑니다.|ラウンドを突破するたびに3ダブロンが貯まる。売ると受け取れる。|Каждый пройденный раунд кладёт внутрь 3 дублона. Продай её — и они твои.|Każda zaliczona runda wrzuca do środka 3 dublony. Sprzedaj ją, by je zabrać.", { bank: 3 });   // tanda 9: junta el Cajero y el Banquero; lo de dentro va en run.hucha

  /* ---------------------------------------------------------------- supervivencia */
  def("shield", "s_palm", 7, 1, "Red de seguridad|Safety net|Filet de sécurité|Rede de segurança|Sicherheitsnetz|Rete di sicurezza||安全网|안전망|セーフティネット|Страховочная сетка|Siatka asekuracyjna", "Una vez por acto, fallar una ronda no te cuesta provisión.|Once per act, failing a round doesn't cost you a provision.|Une fois par acte, rater une manche ne te coûte pas de provision.|Uma vez por ato, falhar uma rodada não te custa provisão.|Einmal pro Akt kostet dich eine verlorene Runde keinen Proviant.|Una volta per atto, fallire un round non ti costa provviste.||每幕一次，回合失败不会消耗补给。|막마다 한 번, 라운드에 실패해도 식량을 잃지 않습니다.|各幕に1回、ラウンドに失敗しても食料を失わない。|Раз за акт провал раунда не отнимает запас.|Raz na akt przegrana runda nie kosztuje cię zapasu.", { shieldAct: true });   // tanda 9: antes "Seguro" (se llamaba casi igual que el Seguro de ronda de la Barra)
  /* tanda 4: VENTAJAS (ventaja: true). Cambian la regla de la ronda sin sumar puntos; solo cabe una (js/adventure.js, buy) */
  def("streakguard", "s_palm", 6, 1, "Guardarrachas|Streak guard|Garde-série|Guarda-sequência|Serienschutz|Salva-serie||连击护符|연속 기록 지킴이|連続正解ガード|Хранитель серии|Strażnik serii", "Los 2 primeros fallos de cada ronda no rompen tu racha.|The first 2 misses of each round don't break your streak.|Les 2 premiers ratés de chaque manche ne cassent pas ta série.|As 2 primeiras falhas de cada rodada não quebram sua sequência.|Die ersten 2 Fehlschüsse jeder Runde brechen deine Serie nicht.|I primi 2 errori di ogni round non spezzano la tua serie.||每回合前 2 次失误不会打断你的连击。|매 라운드 처음 2번의 실수는 연속 기록을 끊지 않아요.|各ラウンド最初の2回のミスでは連続正解が途切れない。|Первые 2 промаха каждого раунда не прерывают твою серию.|Pierwsze 2 pudła w każdej rundzie nie przerywają twojej serii.", { guard: 2, ventaja: true });
  def("minbet", "s_pin", 6, 1, "Mesa de mínimos|Low-stakes table|Table à petites mises|Mesa de apostas mínimas|Tisch mit Mindesteinsatz|Tavolo a puntata minima||低注桌|최소 베팅 테이블|最低賭け金テーブル|Стол малых ставок|Stół niskich stawek", "El objetivo baja un 7 %, pero el margen paga la mitad de doblones.|Targets drop 7%, but the margin pays half the doubloons.|L'objectif baisse de 7 %, mais la marge paie moitié moins de doublons.|A meta cai 7%, mas a margem paga metade dos dobrões.|Das Ziel sinkt um 7 %, aber der Vorsprung bringt nur halb so viele Dublonen.|L'obiettivo scende del 7%, ma il margine paga metà dei dobloni.||目标降低 7%，但超出目标部分的金币奖励减半。|목표가 7% 낮아지지만 초과분은 도블론을 절반만 줘요.|目標が7%下がるが、上乗せのダブロンは半分になる。|Цель ниже на 7 %, но перевес приносит вдвое меньше дублонов.|Cel spada o 7%, ale nadwyżka daje o połowę mniej dublonów.", { round: x => { x.target = (x.target || 1) * 0.93; }, marginHalf: true, ventaja: true });
  def("reball", "s_compass", 7, 1, "Segunda bola|Second ball|Seconde bille|Segunda bola|Zweite Kugel|Seconda pallina||第二颗球|두 번째 공|二投目|Второй шар|Druga kulka", "Dos veces por ronda, si tu clic no hace racha, repites el tiro.|Twice per round, if your click doesn't build a streak, you retake the shot.|Deux fois par manche, si ton clic ne fait pas de série, tu rejoues.|Duas vezes por rodada, se o clique não fizer sequência, você joga de novo.|Zweimal pro Runde: Hält dein Klick die Serie nicht, wirfst du noch mal.|Due volte per round, se il tuo clic non allunga la serie, ritiri.||每回合两次：点击没能延续连击时，可以重投。|라운드마다 두 번, 클릭이 연속 기록을 못 만들면 다시 던져요.|1ラウンド2回まで、クリックで連続正解が続かなければ投げ直せる。|Дважды за раунд: если клик не продлевает серию, бросаешь ещё раз.|Dwa razy na rundę: jeśli klik nie podtrzyma serii, rzucasz jeszcze raz.", { reball: 2, ventaja: true });
  def("sleeve", "s_peak", 9, 2, "As en la manga|Ace up the sleeve|As dans la manche|Ás na manga|Ass im Ärmel|Asso nella manica||袖中王牌|소매 속 에이스|袖の中のエース|Туз в рукаве|As w rękawie", "Juegas un 6.º lugar, difícil, por ronda y tu peor respuesta no cuenta.|You play a hard 6th place each round, and your worst answer doesn't count.|Tu joues un 6e lieu, difficile, par manche, et ta pire réponse ne compte pas.|Você joga um 6.º lugar, difícil, por rodada, e sua pior resposta não conta.|Du spielst pro Runde einen schweren 6. Ort, und deine schlechteste Antwort zählt nicht.|Ogni round giochi un 6° luogo, difficile, e la tua risposta peggiore non conta.||每回合多答一个困难的第 6 个地点，最差的回答不计分。|라운드마다 어려운 6번째 장소를 풀고, 가장 나쁜 답은 빼요.|毎ラウンド難しい6か所目を解き、一番悪い回答は数えない。|В каждом раунде есть трудное 6-е место, и худший ответ не считается.|W każdej rundzie grasz trudne 6. miejsce, a najgorsza odpowiedź się nie liczy.", { sleeve: true, ventaja: true });
  def("heartperk", "s_pin", 9, 2, "Corazón|Heart|Cœur|Coração|Herz|Cuore||红心|하트|ハート|Сердце|Serce", "+1 provisión máxima, y vencer al jefe del acto II te devuelve una.|+1 max provision, and beating the Act II boss gives you one back.|+1 provision maximale, et battre le boss de l'acte II t'en rend une.|+1 provisão máxima, e vencer o chefe do ato II te devolve uma.|+1 maximaler Proviant, und der Sieg über den Boss von Akt II gibt dir einen zurück.|+1 provvista massima, e battere il boss dell'atto II te ne restituisce una.||最大补给 +1，击败第二幕首领时还会还你一份。|최대 식량 +1, 2막 보스를 이기면 하나를 돌려받습니다.|最大食料+1。第2幕のボスを倒すと1つ戻ってくる。|+1 к максимуму запасов, а победа над боссом II акта вернёт один.|+1 do maksymalnych zapasów, a pokonanie bossa II aktu odda ci jeden.", { bossHeal: 1, buy: run => { run.maxLives++; run.lives++; }, sell: run => { run.maxLives = Math.max(1, run.maxLives - 1); run.lives = Math.max(1, Math.min(run.lives - 1, run.maxLives)); } });   // tanda 9: junta Por cuenta de la casa
  def("talisman", "s_compass", 9, 2, "Amuleto del apostador|Gambler's charm|Porte-bonheur du parieur|Amuleto do apostador|Glücksbringer des Spielers|Portafortuna dello scommettitore||赌徒护身符|도박사의 부적|ギャンブラーのお守り|Талисман игрока|Amulet hazardzisty", "El primer reto de cada jefe pierde fuerza (nivel 1).|The first challenge of every boss drops to level 1.|Le premier défi de chaque boss retombe au niveau 1.|O primeiro desafio de cada chefe cai para o nível 1.|Die erste Herausforderung jedes Bosses fällt auf Stufe 1.|La prima sfida di ogni boss scende al livello 1.||每个首领的第一个挑战降至 1 级。|모든 보스의 첫 번째 도전이 1단계로 낮아집니다.|すべてのボスの最初のチャレンジがレベル1に下がる。|Первое испытание каждого босса снижается до 1-го уровня.|Pierwsze wyzwanie każdego bossa spada do poziomu 1.", { softenBoss: 1 });


  /* ---------------------------------------------------------------- v0.11: mas ayudas contra retos de texto, mapa y puntero */

  /* ---------------------------------------------------------------- v0.33: contra los retos de CUARTA PARED */
  def("protector", "s_palm", 4, 0, "Protector|Screen guard|Protège-écran|Película|Schutzfolie|Pellicola||屏幕膜|보호 필름|保護フィルム|Защитное стекло|Szkło ochronne", "Golpes, huellas de grasa y ventanas de error casi no molestan.|Punches, greasy prints and error windows barely get in the way.|Coups, traces grasses et fenêtres d'erreur ne gênent presque plus.|Socos, marcas de gordura e janelas de erro quase não atrapalham.|Schläge, Fettflecken und Fehlerfenster stören kaum noch.|Pugni, ditate unte e finestre di errore non danno quasi fastidio.||拳印、油腻指纹和错误窗口几乎不再碍事。|주먹 자국, 기름 자국, 오류 창이 거의 방해하지 않아요.|パンチ跡、脂の指紋、エラー画面がほとんど邪魔にならない。|Удары, жирные следы и окна ошибок почти не мешают.|Ciosy, tłuste odciski i okna błędów prawie nie przeszkadzają.", { amulet: "pantalla", fx: { glassMul: 0.4, glassBlurMul: 0.2, hangAuto: 1000 } });

  /* ---------------------------------------------------------------- LEGENDARIOS (solo en cofres de jefe) */
  def("philosopher", "s_pin", 14, 3, "Toque de Midas|Midas touch|Toucher de Midas|Toque de Midas|Midas-Touch|Tocco di Mida||点金手|미다스의 손|ミダスの手|Прикосновение Мидаса|Dotyk Midasa", "Cada 10 doblones que guardas bajan el objetivo un 2 % (hasta −10 %).|Every 10 doubloons you keep lower the target by 2% (up to −10%).|Chaque tranche de 10 doublons gardés baisse l'objectif de 2 % (jusqu'à −10 %).|Cada 10 dobrões guardados baixam a meta em 2% (até −10%).|Je 10 gesparte Dublonen senken das Ziel um 2 % (bis −10 %).|Ogni 10 dobloni che tieni abbassano l'obiettivo del 2% (fino a −10%).||每存 10 金币，目标降低 2%（最多 −10%）。|도블론을 10개 모을 때마다 목표가 2% 내려갑니다 (최대 −10%).|ダブロンを10枚貯めるごとに目標が2%下がる（最大−10%）。|Каждые 10 сбережённых дублонов снижают цель на 2% (до −10%).|Każde 10 zachowanych dublonów obniża cel o 2% (do −10%).", { midas: true, round: (x, run) => { x.target = (x.target || 1) * (1 - Math.min(0.1, 0.02 * Math.floor(((run.coins || 0) + (run.hucha || 0)) / 10))); } });   // tanda 12: el dinero guardado baja el objetivo (antes duplicaba un dinero que sobraba)
  def("oracle", "s_palm", 14, 3, "Dividir|Split|Partager|Dividir|Teilen|Dividi||分牌|스플릿|スプリット|Сплит|Rozdziel", "En la pregunta difícil de cada ronda, eliges entre dos lugares.|In each round's hard question, you choose between two places.|À la question difficile de chaque manche, tu choisis entre deux lieux.|Na pergunta difícil de cada rodada, você escolhe entre dois lugares.|Bei der schweren Frage jeder Runde wählst du zwischen zwei Orten.|Nella domanda difficile di ogni round, scegli tra due luoghi.||每回合的难题中，你可以在两个地点里选一个。|각 라운드의 어려운 문제에서 두 장소 중 하나를 고릅니다.|各ラウンドの難問で、2つの場所から選べる。|В трудном вопросе каждого раунда выбираешь одно из двух мест.|W trudnym pytaniu każdej rundy wybierasz jedno z dwóch miejsc.", { split: true });   // tanda 12b: el "split" del blackjack (antes, el Oraculo iluminaba un pais que ya estaba escrito)
  def("masterkey", "s_peak", 14, 3, "Comodín|Wildcard|Joker|Coringa|Joker|Jolly||百搭牌|와일드카드|ワイルドカード|Джокер|Dżoker", "El reto más fuerte de cada ronda no sale.|The strongest challenge of each round doesn't show up.|Le défi le plus fort de chaque manche ne sort pas.|O desafio mais forte de cada rodada não aparece.|Die stärkste Herausforderung jeder Runde fällt weg.|La sfida più forte di ogni round non esce.||每回合最强的挑战不会出现。|매 라운드 가장 강한 도전이 나오지 않아요.|各ラウンドで一番強いチャレンジが出ない。|Самое сильное испытание каждого раунда не выпадает.|Najsilniejsze wyzwanie każdej rundy nie wypada.", { skipHardest: 1 });

  A.RELICS = P;
  A.RELIC_IDS = Object.keys(P);
})(window.AIQ);
/* Reto diario (tanda 3, S14): las reliquias que pueden tocar de regalo, en orden FIJO (lo nuevo, al final): quitar o anadir reliquias al catalogo
   no cambia el regalo de los demas dias. Ni Ventajas, ni Pacto, ni apuestas, ni legendarias */
window.AIQ.DAILY_GIFTS = ["boots", "purse", "hoard", "coupon", "sextant", "almanac", "sonarplus", "compass16", "spyhole", "medkit", "steadyhand", "dictionary", "miner", "divingmask", "plates", "protector", "coolhead"];   // tanda 9: lo nuevo, al final
