/* Geolite · tips: textos de los tooltips del HUD (se calculan al pasar el puntero: siempre en el idioma y con los numeros actuales).
 *  Formato de idioma: "es|en|fr|pt|de|it|es-419|zh|ko|ja|ru|pl". Uso: <el data-tf="clave"> -> A.tips.clave(el) devuelve "Titulo\nDescripcion". */
(() => {
  "use strict";
  const A = window.AIQ = window.AIQ || {};
  const pick = s => A.pick6(s);
  A.tip6 = pick;
  const tip = (t, d) => () => pick(t) + "\n" + pick(d);
  const run = () => (A.adv && A.adv.run) || null;

  /* atributo data-tt de una ronda del mapa de ruta (route: la ruta barajada del Reto diario, hueco -> ronda original; el jefe sigue en el 4.o hueco) */
  A.roundTip = (i, route) => {
    const R0 = A.ADV && A.ADV.ROUNDS && A.ADV.ROUNDS[route && i < 12 ? route[i] : i], R = R0 && route && i < 12 ? { ...R0, boss: i % 4 === 3 } : R0; if (!R) return "";
    const TN = A.ADV.TOPIC_NAMES, topic = A.tx(TN[R.topic][Math.min(R.tier, TN[R.topic].length - 1)]);
    const boss = pick("Jefe del acto: varios retos a la vez.|Act boss: several challenges at once.|Boss de l'acte : plusieurs défis à la fois.|Chefe do ato: vários desafios ao mesmo tempo.|Akt-Boss: mehrere Herausforderungen gleichzeitig.|Boss dell'atto: più sfide insieme.||本幕首领：多个挑战同时出现。|막 보스: 여러 도전이 한꺼번에.|幕のボス：複数のチャレンジが同時に。|Босс акта: несколько испытаний сразу.|Boss aktu: kilka wyzwań naraz.");
    return A.ttAttr(pick("Ronda|Round|Manche|Rodada|Runde|Round||回合|라운드|ラウンド|Раунд|Runda") + " " + (i + 1) + (R.boss ? " · " + pick("Jefe|Boss|Boss|Chefe|Boss|Boss||首领|보스|ボス|Босс|Boss") : ""), (R.boss ? boss + "\n" : "") + topic);
  };
  /* atributo data-tt de una herramienta o reliquia (kind: "tool" | "perk") */
  A.kitTip = (kind, id) => {
    const o = kind === "tool" ? A.ADV.TOOLS[id] : A.RELICS[id]; return o ? A.ttAttr(A.tx(o.n), A.tx(o.d)) : "";
  };
  Object.assign(A.tips, {
    songprev: tip("Canción anterior|Previous song|Morceau précédent|Música anterior|Vorheriger Song|Brano precedente||上一首|이전 곡|前の曲|Предыдущая песня|Poprzedni utwór",
      "Atajo: flecha izquierda.|Shortcut: left arrow.|Raccourci : flèche gauche.|Atalho: seta esquerda.|Kürzel: Pfeil links.|Scorciatoia: freccia sinistra.||快捷键：左方向键。|단축키: 왼쪽 화살표.|ショートカット：左矢印キー。|Горячая клавиша: стрелка влево.|Skrót: strzałka w lewo."),
    songnext: tip("Canción siguiente|Next song|Morceau suivant|Próxima música|Nächster Song|Brano successivo||下一首|다음 곡|次の曲|Следующая песня|Następny utwór",
      "Atajo: flecha derecha.|Shortcut: right arrow.|Raccourci : flèche droite.|Atalho: seta direita.|Kürzel: Pfeil rechts.|Scorciatoia: freccia destra.||快捷键：右方向键。|단축키: 오른쪽 화살표.|ショートカット：右矢印キー。|Горячая клавиша: стрелка вправо.|Skrót: strzałka w prawo."),
    level: tip("Puntos de la ronda|Round score|Points de la manche|Pontos da rodada|Rundenpunkte|Punti del round||本回合分数|라운드 점수|ラウンドスコア|Очки раунда|Wynik rundy",
      "Tu precisión acumulada en esta ronda: cuanto más cerca del lugar, más puntos.|Your precision so far this round: the closer to the place, the more points.|Ta précision cumulée sur cette manche : plus tu es près du lieu, plus tu gagnes.|Sua precisão acumulada nesta rodada: quanto mais perto do lugar, mais pontos.|Deine bisherige Genauigkeit in dieser Runde: je näher am Ort, desto mehr Punkte.|La tua precisione finora in questo round: più sei vicino al luogo, più punti.||你本回合目前的精准度：离地点越近，得分越高。|이번 라운드 지금까지의 정확도: 장소에 가까울수록 점수가 높아요.|このラウンドでのここまでの精度：場所に近いほど高得点。|Твоя точность в этом раунде: чем ближе к месту, тем больше очков.|Twoja dotychczasowa celność w tej rundzie: im bliżej miejsca, tym więcej punktów."),
    need: tip("Objetivo de la ronda|Round target|Objectif de la manche|Meta da rodada|Rundenziel|Obiettivo del round||本回合目标|라운드 목표|ラウンド目標|Цель раунда|Cel rundy",
      "Puntos que necesitas para superar la ronda. Si no llegas, pierdes una provisión.|Points you need to clear the round. Fall short and you lose a provision.|Points nécessaires pour réussir la manche. Sinon, tu perds une provision.|Pontos necessários para vencer a rodada. Se não chegar, perde uma provisão.|Punkte, die du zum Bestehen brauchst. Sonst verlierst du einen Proviant.|Punti necessari per superare il round. Altrimenti perdi una provvista.||通过本回合所需的分数。达不到就会失去一份补给。|라운드를 클리어하는 데 필요한 점수. 모자라면 식량을 하나 잃어요.|ラウンドクリアに必要なポイント。足りないと食料を1つ失う。|Очки, нужные для прохождения раунда. Не хватит — потеряешь запас.|Punkty potrzebne do zaliczenia rundy. Jeśli zabraknie, tracisz zapas."),
    total: tip("Total|Total|Total|Total|Gesamt|Totale||总计|총점|合計|Итого|Razem",
      "Puntos acumulados en toda la partida.|Points collected across the whole game.|Points cumulés sur toute la partie.|Pontos acumulados em toda a partida.|Alle Punkte der gesamten Partie.|Punti accumulati in tutta la partita.||整局游戏累计获得的分数。|게임 전체에서 모은 점수.|ゲーム全体で集めたポイント。|Очки, набранные за всю игру.|Punkty zebrane w całej grze."),
    streak: tip("Racha|Streak|Série|Sequência|Serie|Serie||连击|연속 기록|連続正解|Серия|Seria",
      "Aciertos seguidos. Una racha larga multiplica los puntos de cada pregunta; un fallo la corta.|Correct answers in a row. A long streak multiplies each question's points; a miss breaks it.|Bonnes réponses d'affilée. Une longue série multiplie les points ; une erreur la brise.|Acertos seguidos. Uma sequência longa multiplica os pontos; um erro a quebra.|Treffer in Folge. Eine lange Serie multipliziert die Punkte; ein Fehler bricht sie.|Risposte giuste di fila. Una serie lunga moltiplica i punti; un errore la spezza.||连续答对的次数。连击越长，每题得分倍率越高；一次失误就会中断。|연속 정답 수. 연속 기록이 길수록 문제당 점수가 배가되며, 한 번 틀리면 끊깁니다.|連続正解の数。長く続くほど各問のポイントが倍増し、外すと途切れる。|Правильные ответы подряд. Длинная серия умножает очки за вопрос; промах её обрывает.|Dobre odpowiedzi z rzędu. Długa seria mnoży punkty za każde pytanie; pudło ją przerywa."),
    clock: tip("Tiempo|Time|Temps|Tempo|Zeit|Tempo||时间|시간|時間|Время|Czas",
      "Segundos que te quedan para colocar el pin.|Seconds left to place your pin.|Secondes restantes pour poser ton épingle.|Segundos restantes para colocar o pino.|Sekunden, um deinen Pin zu setzen.|Secondi rimasti per piazzare il pin.||放置图钉的剩余秒数。|핀을 놓을 수 있는 남은 시간(초).|ピンを置くまでの残り秒数。|Сколько секунд осталось, чтобы поставить метку.|Ile sekund zostało na wbicie pinezki."),
    pips: tip("Preguntas de la ronda|Round questions|Questions de la manche|Perguntas da rodada|Fragen der Runde|Domande del round||本回合题目|라운드 문제|ラウンドの問題|Вопросы раунда|Pytania w rundzie",
      "Una marca por pregunta.|One mark per question.|Une marque par question.|Uma marca por pergunta.|Eine Markierung pro Frage.|Un segno per domanda.||每题一个标记。|문제마다 표시 하나.|1問につき1つの印。|Одна отметка на вопрос.|Jeden znacznik na pytanie."),
    kind: tip("Tipo de lugar|Kind of place|Type de lieu|Tipo de lugar|Art des Ortes|Tipo di luogo||地点类型|장소 종류|場所の種類|Тип места|Rodzaj miejsca",
      "Lo que buscas: país, capital, ciudad, monumento…|What you're looking for: country, capital, city, landmark…|Ce que tu cherches : pays, capitale, ville, monument…|O que você procura: país, capital, cidade, monumento…|Was du suchst: Land, Hauptstadt, Stadt, Wahrzeichen…|Cosa cerchi: paese, capitale, città, monumento…||你要找的：国家、首都、城市、地标……|찾는 대상: 국가, 수도, 도시, 랜드마크…|探しているもの：国、首都、都市、名所…|Что ты ищешь: страна, столица, город, достопримечательность…|Czego szukasz: kraju, stolicy, miasta, zabytku…"),
    abact: () => { const r = run(); return pick("Acto|Act|Acte|Ato|Akt|Atto||幕|막|幕|Акт|Akt") + (r ? " " + (r.act + 1) + "/3" : "") + "\n" + pick("Tres actos de cuatro rondas; la última de cada acto es un jefe.|Three acts of four rounds; the last one of each act is a boss.|Trois actes de quatre manches ; la dernière de chaque acte est un boss.|Três atos de quatro rodadas; a última de cada ato é um chefe.|Drei Akte mit je vier Runden; die letzte jedes Aktes ist ein Boss.|Tre atti di quattro round; l'ultimo di ogni atto è un boss.||共三幕，每幕四回合；每幕最后一回合是首领战。|4라운드씩 3막이며, 각 막의 마지막 라운드는 보스입니다.|4ラウンドずつの3幕。各幕の最後はボス。|Три акта по четыре раунда; последний в каждом акте — босс.|Trzy akty po cztery rundy; ostatnia w każdym akcie to boss."); },
    abcoins: () => { const r = run(); return pick("Doblones|Doubloons|Doublons|Dobrões|Dublonen|Dobloni||金币|도블론|ダブロン|Дублоны|Dublony") + (r ? ": " + r.coins : "") + "\n" + pick("Moneda del casino: compra reliquias, herramientas, provisiones y sobornos en el Campamento.|Casino currency: buy relics, tools, provisions and bribes at the Camp.|Monnaie du casino : achète reliques, outils, provisions et pots-de-vin au Campement.|Moeda do cassino: compre relíquias, ferramentas, provisões e subornos no Acampamento.|Casino-Währung: Kaufe im Lager Relikte, Werkzeuge, Proviant und Bestechungen.|Valuta del casinò: compra reliquie, strumenti, provviste e tangenti all'Accampamento.||赌场货币：在营地购买遗物、工具、补给和贿赂。|카지노 화폐: 캠프에서 유물, 도구, 식량, 매수를 구입합니다.|カジノ通貨：キャンプでレリック、道具、食料、買収に使う。|Валюта казино: в Лагере на неё покупают реликвии, инструменты, запасы и взятки.|Waluta kasyna: w Obozie kupisz za nią relikty, narzędzia, zapasy i łapówki."); },
    abhearts: () => { const r = run(); return pick("Provisiones|Provisions|Provisions|Provisões|Proviant|Provviste||补给|식량|食料|Запасы|Zapasy") + (r ? ": " + r.lives + "/" + r.maxLives : "") + "\n" + pick("Si no superas una ronda pierdes una. Sin provisiones, la expedición termina.|Fail a round and you lose one. With none left, the expedition ends.|Rate une manche et tu en perds une. Sans provisions, l'expédition se termine.|Se falhar uma rodada, você perde uma. Sem provisões, a expedição termina.|Verpatzt du eine Runde, verlierst du einen. Ohne Proviant endet die Expedition.|Se fallisci un round ne perdi una. Senza provviste la spedizione finisce.||一回合失败就会失去一份。全部用完，远征就结束了。|라운드에 실패하면 식량을 하나 잃어요. 식량이 없으면 원정이 끝나요.|ラウンドに失敗すると1つ失う。なくなると遠征は終わり。|Провалишь раунд — потеряешь один. Кончатся все — экспедиция окончена.|Oblejesz rundę — tracisz jeden. Gdy się skończą, wyprawa dobiega końca."); },
  });
  /* el Clasico no tiene provisiones ni multiplicador de racha: si no llegas a la meta repites el nivel, y la racha solo cuenta aciertos seguidos */
  const inAdv = () => !!(A.core && A.core.S && A.core.S.run), needAdv = A.tips.need, streakAdv = A.tips.streak;
  const needCl = tip("Objetivo del nivel|Level target|Objectif du niveau|Meta do nível|Level-Ziel|Obiettivo del livello||本关目标|레벨 목표|レベル目標|Цель уровня|Cel poziomu",
    "Puntos que necesitas para superar el nivel. Si no llegas, tendrás que repetirlo.|Points you need to clear the level. Fall short and you'll have to replay it.|Points nécessaires pour réussir le niveau. Sinon, il faudra le rejouer.|Pontos necessários para passar de nível. Se não chegar, terá de repeti-lo.|Punkte, die du für das Level brauchst. Sonst musst du es wiederholen.|Punti necessari per superare il livello. Altrimenti dovrai rigiocarlo.||通过本关所需的分数。达不到就得重玩这一关。|레벨을 통과하는 데 필요한 점수. 모자라면 다시 도전해야 해요.|レベルクリアに必要なポイント。足りないとやり直し。|Очки, нужные для прохождения уровня. Не хватит — придётся переигрывать.|Punkty potrzebne do zaliczenia poziomu. Jeśli zabraknie, trzeba go powtórzyć.");
  const streakCl = tip("Racha|Streak|Série|Sequência|Serie|Serie||连击|연속 기록|連続正解|Серия|Seria",
    "Aciertos seguidos. Un fallo la corta.|Correct answers in a row. A miss breaks it.|Bonnes réponses d'affilée. Une erreur la brise.|Acertos seguidos. Um erro a quebra.|Treffer in Folge. Ein Fehler bricht sie.|Risposte giuste di fila. Un errore la spezza.||连续答对的次数。一次失误就会中断。|연속 정답 수. 한 번 틀리면 끊깁니다.|連続正解の数。外すと途切れる。|Правильные ответы подряд. Промах её обрывает.|Dobre odpowiedzi z rzędu. Pudło ją przerywa.");
  A.tips.need = () => (inAdv() ? needAdv() : needCl());
  A.tips.streak = () => (inAdv() ? streakAdv() : streakCl());
})();
